[package]
name = "rf_config_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
rand = "0.9.1"
rfd = "0.15.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
